1. Represent the data in the given sheet into an appropriate NumPy array so
that you can perform the following actions on it.

In [1]:
import numpy as np

In [2]:
import numpy as np

a = np.array([[
        
            [[9, 20], [13, 31], [8, 21], [13, 25], [9, 29], [15, 20], [10, 25]],
            [[13, 23], [9, 23], [13, 21], [-13, 32], [15, 25], [13, 31], [15, 29]],
            [[9, 24], [6, 26], [79, 30], [10, 30], [7, 30], [12, 22], [11, 32]],
            [[13, 30], [12, 26], [15, 26], [15, 29], [8, 25], [11, 27], [15, 24]]
        
    ],
    
    [
        
            [[6, 20], [13, 32], [13, 28], [15, 25], [10, 31], [12, 23], [13, 30]],
            [[9, 32], [6, 32], [8, 30], [7, 32], [7, 32], [14, 29], [9, 21]],
            [[14, 23], [11, 23], [14, 29], [15, 23], [15, 30], [10, 31], [13, 30]],
            [[13, 24], [10, 29], [12, 24], [6, 31], [13, 31], [13, 29], [7, 25]]
        
    ],
    [
        
            [[8, 18], [4, 19], [6, 18], [2, 22], [2, 18], [2, 5], [21, 5]],
            [[7, 20], [3, 21], [3, 20], [5, 20], [3, 18], [2, 6], [20, 6]],
            [[4, 19], [5, 21], [5, 18], [5, 21], [3, 19], [7, 6], [22, 4]],
            [[8, 22], [2, 20], [2, 22], [4, 20], [7, 22], [7, 2], [22, 5]]
        
    ],
    [
        
            [[7, 22], [10, 19], [-10, 18], [11, 20], [8, 20], [9, 71], [22, 10]],
            [[8, 22], [9, 21], [10, 22], [8, 19], [9, 18], [11, 11], [18, 11]],
            [[8, 21], [11, 20], [8, 22], [10, 18], [7, 18], [7, 7], [19, 7]],
            [[7, 19], [9, 22], [8, 22], [11, 18], [12, 22], [8, 11], [21, 8]]
        
    ]])
print(a)

[[[[  9  20]
   [ 13  31]
   [  8  21]
   [ 13  25]
   [  9  29]
   [ 15  20]
   [ 10  25]]

  [[ 13  23]
   [  9  23]
   [ 13  21]
   [-13  32]
   [ 15  25]
   [ 13  31]
   [ 15  29]]

  [[  9  24]
   [  6  26]
   [ 79  30]
   [ 10  30]
   [  7  30]
   [ 12  22]
   [ 11  32]]

  [[ 13  30]
   [ 12  26]
   [ 15  26]
   [ 15  29]
   [  8  25]
   [ 11  27]
   [ 15  24]]]


 [[[  6  20]
   [ 13  32]
   [ 13  28]
   [ 15  25]
   [ 10  31]
   [ 12  23]
   [ 13  30]]

  [[  9  32]
   [  6  32]
   [  8  30]
   [  7  32]
   [  7  32]
   [ 14  29]
   [  9  21]]

  [[ 14  23]
   [ 11  23]
   [ 14  29]
   [ 15  23]
   [ 15  30]
   [ 10  31]
   [ 13  30]]

  [[ 13  24]
   [ 10  29]
   [ 12  24]
   [  6  31]
   [ 13  31]
   [ 13  29]
   [  7  25]]]


 [[[  8  18]
   [  4  19]
   [  6  18]
   [  2  22]
   [  2  18]
   [  2   5]
   [ 21   5]]

  [[  7  20]
   [  3  21]
   [  3  20]
   [  5  20]
   [  3  18]
   [  2   6]
   [ 20   6]]

  [[  4  19]
   [  5  21]
   [  5  18]
   [  5  21]
   [  3  19]
   [  7   6]
   [ 22   4]]

  [[  8  22]
   [  2  20]
   [  2  22]
   [  4  20]
   [  7  22]
   [  7   2]
   [ 22   5]]]


 [[[  7  22]
   [ 10  19]
   [-10  18]
   [ 11  20]
   [  8  20]
   [  9  71]
   [ 22  10]]

  [[  8  22]
   [  9  21]
   [ 10  22]
   [  8  19]
   [  9  18]
   [ 11  11]
   [ 18  11]]

  [[  8  21]
   [ 11  20]
   [  8  22]
   [ 10  18]
   [  7  18]
   [  7   7]
   [ 19   7]]

  [[  7  19]
   [  9  22]
   [  8  22]
   [ 11  18]
   [ 12  22]
   [  8  11]
   [ 21   8]]]]

2. Write the dimensions and shape of the NumPy array that you have
created.

In [3]:
print(a.ndim)
print(a.shape)
np.amax(a)

4
(4, 4, 7, 2)

79

3. Print the daily temperatures for the first week of each month.

In [4]:
print(a[0:, 0, 0:, 0:])

[[[  9  20]
  [ 13  31]
  [  8  21]
  [ 13  25]
  [  9  29]
  [ 15  20]
  [ 10  25]]

 [[  6  20]
  [ 13  32]
  [ 13  28]
  [ 15  25]
  [ 10  31]
  [ 12  23]
  [ 13  30]]

 [[  8  18]
  [  4  19]
  [  6  18]
  [  2  22]
  [  2  18]
  [  2   5]
  [ 21   5]]

 [[  7  22]
  [ 10  19]
  [-10  18]
  [ 11  20]
  [  8  20]
  [  9  71]
  [ 22  10]]]

4. Print the temperatures for Tuesday of each month.

In [5]:
print(a[0:, 0:, 1, 0:])

[[[13 31]
  [ 9 23]
  [ 6 26]
  [12 26]]

 [[13 32]
  [ 6 32]
  [11 23]
  [10 29]]

 [[ 4 19]
  [ 3 21]
  [ 5 21]
  [ 2 20]]

 [[10 19]
  [ 9 21]
  [11 20]
  [ 9 22]]]

5. Print only the maximum temperature for all the weekdays of Dec and Feb.

In [6]:
print(a[1:4:2, 0:, 0:, 1])

[[[20 32 28 25 31 23 30]
  [32 32 30 32 32 29 21]
  [23 23 29 23 30 31 30]
  [24 29 24 31 31 29 25]]

 [[22 19 18 20 20 71 10]
  [22 21 22 19 18 11 11]
  [21 20 22 18 18  7  7]
  [19 22 22 18 22 11  8]]]

6. Print all the days along with the week number in November when the
minimum temperature was less than 8 degrees.

In [7]:
c=a[0, 0:, 0:, 0]

b=(a[0, 0:, 0:, 0]) < 8  #filtering mini temp less than 8 degrees.

print(c[b])

[-13   6   7]

In [8]:
# week2,Thur, -13
print(c) # returns 2D array

[[  9  13   8  13   9  15  10]
 [ 13   9  13 -13  15  13  15]
 [  9   6  79  10   7  12  11]
 [ 13  12  15  15   8  11  15]]

In [9]:
d= np.where(c<8)  # return indexes of values according to given condition in where func 
print(d)

(array([1, 2, 2], dtype=int64), array([3, 1, 4], dtype=int64))

In [10]:
days={0:"Mon", 1:"Tues", 2:"Wed", 3:"Thurs", 4:"Fri", 5:"Sat", 6:"Sun"}
for i in range(len(d[0])):
    print('week: ',(d[0][i])+1, 'day: ',days[d[1][i]])

week:  2 day:  Thurs
week:  3 day:  Tues
week:  3 day:  Fri

7. Print all the weeks in Dec and Jan where the maximum temperature has
crossed a threshold of 20 degrees.

In [11]:
l=[1,2]  #filtering Dec and Jan months
c=a[l, 0:, 0:, 1]
s=(a[l, 0:, 0:, 1]) > 20
print(c[s])   #returns all those values of max temp who has crossed a threshold of 20 deg.

[32 28 25 31 23 30 32 32 30 32 32 29 21 23 23 29 23 30 31 30 24 29 24 31
 31 29 25 22 21 21 21 22 22 22]

In [12]:
print(c)  #returns 3D

[[[20 32 28 25 31 23 30]
  [32 32 30 32 32 29 21]
  [23 23 29 23 30 31 30]
  [24 29 24 31 31 29 25]]

 [[18 19 18 22 18  5  5]
  [20 21 20 20 18  6  6]
  [19 21 18 21 19  6  4]
  [22 20 22 20 22  2  5]]]

In [13]:
d=np.where(c>20)  #return indexes
print(d)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1], dtype=int64), array([0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 0, 1, 2, 2, 3, 3, 3], dtype=int64), array([1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1, 2, 3, 4, 5, 6, 0, 1,
       2, 3, 4, 5, 6, 3, 1, 1, 3, 0, 2, 4], dtype=int64))

In [14]:
# for December month
for i in range(len(d[0])):
    print('week: ',d[0][i]+1, " of December month ")
    print('week: ',d[1][i]+1, " of January month ")

week:  1  of December month
week:  1  of January month
week:  1  of December month
week:  1  of January month
week:  1  of December month
week:  1  of January month
week:  1  of December month
week:  1  of January month
week:  1  of December month
week:  1  of January month
week:  1  of December month
week:  1  of January month
week:  1  of December month
week:  2  of January month
week:  1  of December month
week:  2  of January month
week:  1  of December month
week:  2  of January month
week:  1  of December month
week:  2  of January month
week:  1  of December month
week:  2  of January month
week:  1  of December month
week:  2  of January month
week:  1  of December month
week:  2  of January month
week:  1  of December month
week:  3  of January month
week:  1  of December month
week:  3  of January month
week:  1  of December month
week:  3  of January month
week:  1  of December month
week:  3  of January month
week:  1  of December month
week:  3  of January month
week:  1  of December month
week:  3  of January month
week:  1  of December month
week:  3  of January month
week:  1  of December month
week:  4  of January month
week:  1  of December month
week:  4  of January month
week:  1  of December month
week:  4  of January month
week:  1  of December month
week:  4  of January month
week:  1  of December month
week:  4  of January month
week:  1  of December month
week:  4  of January month
week:  1  of December month
week:  4  of January month
week:  2  of December month
week:  1  of January month
week:  2  of December month
week:  2  of January month
week:  2  of December month
week:  3  of January month
week:  2  of December month
week:  3  of January month
week:  2  of December month
week:  4  of January month
week:  2  of December month
week:  4  of January month
week:  2  of December month
week:  4  of January month

8. Check if there are any absurd values present in the dataset(like some temp
which should not be present in the data)

In [15]:
Q1=np.percentile(a,25)                #-1.5*IQR(Q3-Q1)
Q3=np.percentile(a,75)
lower_range=Q1-(1.5*(Q3-Q1))
upper_range=Q3+(1.5*(Q3-Q1))
print("lower range: ", lower_range)
print("upper range: ", upper_range)
upper=a>upper_range
lower=a<lower_range
print("outliers are :")
u=a[upper]
l=a[lower]

    
print(u,l)

if u.all() or l.all():
    print("absured values present in the dataset:")

lower range:  -13.0
upper range:  43.0
outliers are :
[79 71] []
absured values present in the dataset:

9. What strategy would you use to handle such data points?
solution: Removing outliers involves identifying data points that deviate significantly from the main distribution due to errors,noise, or anomalies. Once identified, outliers can be removed by replacing them with appropriate values.
This process helps improve the accuracy and reliability of analysis and modeling by reducing the distortion
caused by extreme values. The choice of appropriate values depends on the context of the data and the specific method
used for replacement, such as using statistical measures like mean, median, or more sophisticated techniques.

10. Find and print the indexes of all the outlier(unusual) values present in
the above dataset.

In [16]:
d=np.where(a==u)
e=np.where(a==l)
print("the indexes of all the outliers of upper range: \n",d, " the indexes of all the outliers of lower range: \n ", e)

the indexes of all the outliers of upper range:
 (array([0, 3], dtype=int64), array([2, 0], dtype=int64), array([2, 5], dtype=int64), array([0, 1], dtype=int64))  the indexes of all the outliers of lower range:
  (array([], dtype=int64),)

C:\Users\Shyam Singh\AppData\Local\Temp\ipykernel_22032\1463739337.py:2: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  e=np.where(a==l)

11.Replace the outliers with an appropriate value.

In [17]:
a[0, 2, 2, 0] = 50 #updating first outliers
a[3,0,5,1] =  25  #updating second outliers
print(a[0, 2, 2, 0])
print(a[3,0,5,1])

50
25

In [18]:
print(a) # outliers are removed by appropriate values

[[[[  9  20]
   [ 13  31]
   [  8  21]
   [ 13  25]
   [  9  29]
   [ 15  20]
   [ 10  25]]

  [[ 13  23]
   [  9  23]
   [ 13  21]
   [-13  32]
   [ 15  25]
   [ 13  31]
   [ 15  29]]

  [[  9  24]
   [  6  26]
   [ 50  30]
   [ 10  30]
   [  7  30]
   [ 12  22]
   [ 11  32]]

  [[ 13  30]
   [ 12  26]
   [ 15  26]
   [ 15  29]
   [  8  25]
   [ 11  27]
   [ 15  24]]]


 [[[  6  20]
   [ 13  32]
   [ 13  28]
   [ 15  25]
   [ 10  31]
   [ 12  23]
   [ 13  30]]

  [[  9  32]
   [  6  32]
   [  8  30]
   [  7  32]
   [  7  32]
   [ 14  29]
   [  9  21]]

  [[ 14  23]
   [ 11  23]
   [ 14  29]
   [ 15  23]
   [ 15  30]
   [ 10  31]
   [ 13  30]]

  [[ 13  24]
   [ 10  29]
   [ 12  24]
   [  6  31]
   [ 13  31]
   [ 13  29]
   [  7  25]]]


 [[[  8  18]
   [  4  19]
   [  6  18]
   [  2  22]
   [  2  18]
   [  2   5]
   [ 21   5]]

  [[  7  20]
   [  3  21]
   [  3  20]
   [  5  20]
   [  3  18]
   [  2   6]
   [ 20   6]]

  [[  4  19]
   [  5  21]
   [  5  18]
   [  5  21]
   [  3  19]
   [  7   6]
   [ 22   4]]

  [[  8  22]
   [  2  20]
   [  2  22]
   [  4  20]
   [  7  22]
   [  7   2]
   [ 22   5]]]


 [[[  7  22]
   [ 10  19]
   [-10  18]
   [ 11  20]
   [  8  20]
   [  9  25]
   [ 22  10]]

  [[  8  22]
   [  9  21]
   [ 10  22]
   [  8  19]
   [  9  18]
   [ 11  11]
   [ 18  11]]

  [[  8  21]
   [ 11  20]
   [  8  22]
   [ 10  18]
   [  7  18]
   [  7   7]
   [ 19   7]]

  [[  7  19]
   [  9  22]
   [  8  22]
   [ 11  18]
   [ 12  22]
   [  8  11]
   [ 21   8]]]]

12. Find the average max temperature for the winter months in Jaipur.

In [19]:

c=a[1, 0:, 0:, 1] # for Dec months of max temp
c=a[2, 0:, 0:, 1] # for Jan months of max temp
print("average of max temp of Dec months of jaipur\n",np.mean(c))
print("average of max temp of Jan months of jaipur\n",np.mean(c))

average of max temp of Dec months of jaipur
 15.607142857142858
average of max temp of Jan months of jaipur
 15.607142857142858

13. Find the weekly min avg temp for the month of Dec in Jaipur

In [20]:
c=a[1, 0:, 0:, 0]
print(c)
print(np.mean(c, axis=1))

[[ 6 13 13 15 10 12 13]
 [ 9  6  8  7  7 14  9]
 [14 11 14 15 15 10 13]
 [13 10 12  6 13 13  7]]
[11.71428571  8.57142857 13.14285714 10.57142857]

14. Find the overall avg temp for the months Dec and Jan

In [21]:
l=[1,2]  #filtering Dec and Jan months
c=a[l, 0:, 0:, 1]

print("winter months of Dec and Jan:\n", np.mean(c))

winter months of Dec and Jan:
 21.714285714285715

15. Find the least temp experienced by the city in the month of Dec and
Jan. Also print the exact date( Day/Week/Month) for the same.

In [22]:
l=[1,2]  #filtering Dec and Jan months
c=a[l, 0:, 0:, 0]
print("the least temp experienced by the city in the month of Dec and Jan: ",c.min())

#finding indexe of least temp
print("\nindexes when least temp experienced:\n")
d=np.where(c==np.amin(c))
print(d)
months={0:"Nov", 1:"Dec", 2:"Jan", 3:"Feb"}
weeks={0:"week 1", 1:"week 2", 2:"week 3", 3:"week 4"}
days={0:"Mon", 1:"Tues", 2:"Wed", 3:"Thurs", 4:"Fri", 5:"Sat", 6:"Sun"}
print("\nThe exact date when least temp experienced by the city in the months of dec and jan.:\n")
for i in range(len(d[0])):
    print(days[d[2][i]], "/",weeks[d[1][i]],"/", months[d[0][i]])

the least temp experienced by the city in the month of Dec and Jan:  2

indexes when least temp experienced:

(array([1, 1, 1, 1, 1, 1], dtype=int64), array([0, 0, 0, 1, 3, 3], dtype=int64), array([3, 4, 5, 5, 1, 2], dtype=int64))

The exact date when least temp experienced by the city in the months of dec and jan.:

Thurs / week 1 / Dec
Fri / week 1 / Dec
Sat / week 1 / Dec
Sat / week 2 / Dec
Tues / week 4 / Dec
Wed / week 4 / Dec

16. Find the max temp in the month of Feb and return its
date(Day/Week/Month)

In [23]:
c=a[3, 0:, 0:, 1]
# print("max temp in the month of Feb: ", np.max(c))
x=np.where(c==np.max(c))
print(x)
days={0:"Mon", 1:"Tues", 2:"Wed", 3:"Thurs", 4:"Fri", 5:"Sat", 6:"Sun"}
print("Maximum Temperature in the month of Feb is ", np.max(c),"in",days[x[1][0]], "/",x[0][0], "/Feb")

(array([0], dtype=int64), array([5], dtype=int64))
Maximum Temperature in the month of Feb is  25 in Sat / 0 /Feb

17. Find the days in the month of Nov where the max temp of the day
dropped below the avg temp of the month. As

In [24]:
c=a[0, 0:, 0:, 1] #for the month of Nov
d=c<c.mean()
print("the max temp of the day dropped below the avg temp of the month of Nov: ", c[d])

id=np.where(d)  #finding the indexes of the temp below than avg temp of month
print(id)

days={0:"Mon", 1:"Tues", 2:"Wed", 3:"Thurs", 4:"Fri", 5:"Sat", 6:"Sun"}
weeks={0:"week 1", 1:"week 2", 2:"week 3", 3:"week 4"}
for i in range(len(id[0])):
    print(days[id[1][i]], "of", weeks[id[0][i]])

the max temp of the day dropped below the avg temp of the month of Nov:  [20 21 25 20 25 23 23 21 25 24 26 22 26 26 25 24]
(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3], dtype=int64), array([0, 2, 3, 5, 6, 0, 1, 2, 4, 0, 1, 5, 1, 2, 4, 6], dtype=int64))
Mon of week 1
Wed of week 1
Thurs of week 1
Sat of week 1
Sun of week 1
Mon of week 2
Tues of week 2
Wed of week 2
Fri of week 2
Mon of week 3
Tues of week 3
Sat of week 3
Tues of week 4
Wed of week 4
Fri of week 4
Sun of week 4

18. Convert the above dataset into an array where the weeks of the same
month must be present in the same row, but belonging to different months
should come in a row either below or above the selected month.

In [25]:
c1=a[0, 0:, 0:,0:].reshape(1,56) #first month Nov
c2=a[1, 0:, 0:,0:].reshape(1,56) #second month Dec
c3=a[2, 0:, 0:,0:].reshape(1,56) #third month Jan
c4=a[3, 0:, 0:,0:].reshape(1,56) #fourth month Feb

c5 = np.concatenate((c1,c2,c3,c4)) #concatenate all months individually so that all weeks of the same month must be in one row.
print(c5)

[[  9  20  13  31   8  21  13  25   9  29  15  20  10  25  13  23   9  23
   13  21 -13  32  15  25  13  31  15  29   9  24   6  26  50  30  10  30
    7  30  12  22  11  32  13  30  12  26  15  26  15  29   8  25  11  27
   15  24]
 [  6  20  13  32  13  28  15  25  10  31  12  23  13  30   9  32   6  32
    8  30   7  32   7  32  14  29   9  21  14  23  11  23  14  29  15  23
   15  30  10  31  13  30  13  24  10  29  12  24   6  31  13  31  13  29
    7  25]
 [  8  18   4  19   6  18   2  22   2  18   2   5  21   5   7  20   3  21
    3  20   5  20   3  18   2   6  20   6   4  19   5  21   5  18   5  21
    3  19   7   6  22   4   8  22   2  20   2  22   4  20   7  22   7   2
   22   5]
 [  7  22  10  19 -10  18  11  20   8  20   9  25  22  10   8  22   9  21
   10  22   8  19   9  18  11  11  18  11   8  21  11  20   8  22  10  18
    7  18   7   7  19   7   7  19   9  22   8  22  11  18  12  22   8  11
   21   8]]

19. The above data is appropriate for an audience who follow the metric
system of measurement. Create an array that holds the same data but
presented in Fahrenheit.

In [26]:
# using formulae
feh = (9 * a / 5 + 32)
print("The Following below data in the fahrenheit:\n",feh)

The Following below data in the fahrenheit:
 [[[[ 48.2  68. ]
   [ 55.4  87.8]
   [ 46.4  69.8]
   [ 55.4  77. ]
   [ 48.2  84.2]
   [ 59.   68. ]
   [ 50.   77. ]]

  [[ 55.4  73.4]
   [ 48.2  73.4]
   [ 55.4  69.8]
   [  8.6  89.6]
   [ 59.   77. ]
   [ 55.4  87.8]
   [ 59.   84.2]]

  [[ 48.2  75.2]
   [ 42.8  78.8]
   [122.   86. ]
   [ 50.   86. ]
   [ 44.6  86. ]
   [ 53.6  71.6]
   [ 51.8  89.6]]

  [[ 55.4  86. ]
   [ 53.6  78.8]
   [ 59.   78.8]
   [ 59.   84.2]
   [ 46.4  77. ]
   [ 51.8  80.6]
   [ 59.   75.2]]]


 [[[ 42.8  68. ]
   [ 55.4  89.6]
   [ 55.4  82.4]
   [ 59.   77. ]
   [ 50.   87.8]
   [ 53.6  73.4]
   [ 55.4  86. ]]

  [[ 48.2  89.6]
   [ 42.8  89.6]
   [ 46.4  86. ]
   [ 44.6  89.6]
   [ 44.6  89.6]
   [ 57.2  84.2]
   [ 48.2  69.8]]

  [[ 57.2  73.4]
   [ 51.8  73.4]
   [ 57.2  84.2]
   [ 59.   73.4]
   [ 59.   86. ]
   [ 50.   87.8]
   [ 55.4  86. ]]

  [[ 55.4  75.2]
   [ 50.   84.2]
   [ 53.6  75.2]
   [ 42.8  87.8]
   [ 55.4  87.8]
   [ 55.4  84.2]
   [ 44.6  77. ]]]


 [[[ 46.4  64.4]
   [ 39.2  66.2]
   [ 42.8  64.4]
   [ 35.6  71.6]
   [ 35.6  64.4]
   [ 35.6  41. ]
   [ 69.8  41. ]]

  [[ 44.6  68. ]
   [ 37.4  69.8]
   [ 37.4  68. ]
   [ 41.   68. ]
   [ 37.4  64.4]
   [ 35.6  42.8]
   [ 68.   42.8]]

  [[ 39.2  66.2]
   [ 41.   69.8]
   [ 41.   64.4]
   [ 41.   69.8]
   [ 37.4  66.2]
   [ 44.6  42.8]
   [ 71.6  39.2]]

  [[ 46.4  71.6]
   [ 35.6  68. ]
   [ 35.6  71.6]
   [ 39.2  68. ]
   [ 44.6  71.6]
   [ 44.6  35.6]
   [ 71.6  41. ]]]


 [[[ 44.6  71.6]
   [ 50.   66.2]
   [ 14.   64.4]
   [ 51.8  68. ]
   [ 46.4  68. ]
   [ 48.2  77. ]
   [ 71.6  50. ]]

  [[ 46.4  71.6]
   [ 48.2  69.8]
   [ 50.   71.6]
   [ 46.4  66.2]
   [ 48.2  64.4]
   [ 51.8  51.8]
   [ 64.4  51.8]]

  [[ 46.4  69.8]
   [ 51.8  68. ]
   [ 46.4  71.6]
   [ 50.   64.4]
   [ 44.6  64.4]
   [ 44.6  44.6]
   [ 66.2  44.6]]

  [[ 44.6  66.2]
   [ 48.2  71.6]
   [ 46.4  71.6]
   [ 51.8  64.4]
   [ 53.6  71.6]
   [ 46.4  51.8]
   [ 69.8  46.4]]]]

20. Sort the above data in descending order on the basis of weekly average
for the month of Dec.

In [27]:
d=feh[1,0:,0:,0:]
# c1=feh[1,0, 0:, 0:].mean()
# c2=feh[1,1, 0:, 0:].mean()
# c3=feh[1,2, 0:, 0:].mean()
# c4=feh[1,3, 0:, 0:].mean()
# c5=[c1,c2,c3,c4]
# np.sort(c5)[::-1]
# print(d)
# print(d.shape)
# Calculate the weekly averages for December
dec_weekly_avg = np.mean(d, axis=2)
# print(dec_weekly_avg)
# Calculate the sorting indices in descending order
sorting_indices = np.argsort(np.mean(dec_weekly_avg, axis=1))[::-1]
# print(sorting_indices)

# Sort the weeks based on the sorting indices
sorted_dec_data = d[sorting_indices]

print("Original data for December:\n", d)
print("Sorted data for December based on weekly average:\n", sorted_dec_data)

Original data for December:
 [[[42.8 68. ]
  [55.4 89.6]
  [55.4 82.4]
  [59.  77. ]
  [50.  87.8]
  [53.6 73.4]
  [55.4 86. ]]

 [[48.2 89.6]
  [42.8 89.6]
  [46.4 86. ]
  [44.6 89.6]
  [44.6 89.6]
  [57.2 84.2]
  [48.2 69.8]]

 [[57.2 73.4]
  [51.8 73.4]
  [57.2 84.2]
  [59.  73.4]
  [59.  86. ]
  [50.  87.8]
  [55.4 86. ]]

 [[55.4 75.2]
  [50.  84.2]
  [53.6 75.2]
  [42.8 87.8]
  [55.4 87.8]
  [55.4 84.2]
  [44.6 77. ]]]
Sorted data for December based on weekly average:
 [[[57.2 73.4]
  [51.8 73.4]
  [57.2 84.2]
  [59.  73.4]
  [59.  86. ]
  [50.  87.8]
  [55.4 86. ]]

 [[42.8 68. ]
  [55.4 89.6]
  [55.4 82.4]
  [59.  77. ]
  [50.  87.8]
  [53.6 73.4]
  [55.4 86. ]]

 [[48.2 89.6]
  [42.8 89.6]
  [46.4 86. ]
  [44.6 89.6]
  [44.6 89.6]
  [57.2 84.2]
  [48.2 69.8]]

 [[55.4 75.2]
  [50.  84.2]
  [53.6 75.2]
  [42.8 87.8]
  [55.4 87.8]
  [55.4 84.2]
  [44.6 77. ]]]

21. Sort the temp of the first three days of each month in descending order
on the basis of overall average for the whole winter.

In [43]:
winter_avg = np.mean(a[:, :, :, 0:])  

# Extract temperature data for the first three days of each month
first_three_days = a[:, :, :3, 0:]

# Calculate average temperature for the first three days of each month
avg_first_three_days = np.mean(first_three_days, axis=(2, 3))

# Calculate sorting indices in descending order based on the average temperature
sorting_indices = np.argsort(avg_first_three_days)[::-1]

# Sort the months' data based on the sorting indices
sorted_data = a[sorting_indices]

print("Original data for the first three days of each month:\n", first_three_days)
print("Sorted data based on overall average for the whole winter:\n", sorted_data)

Original data for the first three days of each month:
 [[[[  9  20]
   [ 13  31]
   [  8  21]]

  [[ 13  23]
   [  9  23]
   [ 13  21]]

  [[  9  24]
   [  6  26]
   [ 50  30]]

  [[ 13  30]
   [ 12  26]
   [ 15  26]]]


 [[[  6  20]
   [ 13  32]
   [ 13  28]]

  [[  9  32]
   [  6  32]
   [  8  30]]

  [[ 14  23]
   [ 11  23]
   [ 14  29]]

  [[ 13  24]
   [ 10  29]
   [ 12  24]]]


 [[[  8  18]
   [  4  19]
   [  6  18]]

  [[  7  20]
   [  3  21]
   [  3  20]]

  [[  4  19]
   [  5  21]
   [  5  18]]

  [[  8  22]
   [  2  20]
   [  2  22]]]


 [[[  7  22]
   [ 10  19]
   [-10  18]]

  [[  8  22]
   [  9  21]
   [ 10  22]]

  [[  8  21]
   [ 11  20]
   [  8  22]]

  [[  7  19]
   [  9  22]
   [  8  22]]]]
Sorted data based on overall average for the whole winter:
 [[[[[  9  20]
    [ 13  31]
    [  8  21]
    [ 13  25]
    [  9  29]
    [ 15  20]
    [ 10  25]]

   [[ 13  23]
    [  9  23]
    [ 13  21]
    [-13  32]
    [ 15  25]
    [ 13  31]
    [ 15  29]]

   [[  9  24]
    [  6  26]
    [ 50  30]
    [ 10  30]
    [  7  30]
    [ 12  22]
    [ 11  32]]

   [[ 13  30]
    [ 12  26]
    [ 15  26]
    [ 15  29]
    [  8  25]
    [ 11  27]
    [ 15  24]]]


  [[[  7  22]
    [ 10  19]
    [-10  18]
    [ 11  20]
    [  8  20]
    [  9  25]
    [ 22  10]]

   [[  8  22]
    [  9  21]
    [ 10  22]
    [  8  19]
    [  9  18]
    [ 11  11]
    [ 18  11]]

   [[  8  21]
    [ 11  20]
    [  8  22]
    [ 10  18]
    [  7  18]
    [  7   7]
    [ 19   7]]

   [[  7  19]
    [  9  22]
    [  8  22]
    [ 11  18]
    [ 12  22]
    [  8  11]
    [ 21   8]]]


  [[[  8  18]
    [  4  19]
    [  6  18]
    [  2  22]
    [  2  18]
    [  2   5]
    [ 21   5]]

   [[  7  20]
    [  3  21]
    [  3  20]
    [  5  20]
    [  3  18]
    [  2   6]
    [ 20   6]]

   [[  4  19]
    [  5  21]
    [  5  18]
    [  5  21]
    [  3  19]
    [  7   6]
    [ 22   4]]

   [[  8  22]
    [  2  20]
    [  2  22]
    [  4  20]
    [  7  22]
    [  7   2]
    [ 22   5]]]


  [[[  6  20]
    [ 13  32]
    [ 13  28]
    [ 15  25]
    [ 10  31]
    [ 12  23]
    [ 13  30]]

   [[  9  32]
    [  6  32]
    [  8  30]
    [  7  32]
    [  7  32]
    [ 14  29]
    [  9  21]]

   [[ 14  23]
    [ 11  23]
    [ 14  29]
    [ 15  23]
    [ 15  30]
    [ 10  31]
    [ 13  30]]

   [[ 13  24]
    [ 10  29]
    [ 12  24]
    [  6  31]
    [ 13  31]
    [ 13  29]
    [  7  25]]]]



 [[[[  8  18]
    [  4  19]
    [  6  18]
    [  2  22]
    [  2  18]
    [  2   5]
    [ 21   5]]

   [[  7  20]
    [  3  21]
    [  3  20]
    [  5  20]
    [  3  18]
    [  2   6]
    [ 20   6]]

   [[  4  19]
    [  5  21]
    [  5  18]
    [  5  21]
    [  3  19]
    [  7   6]
    [ 22   4]]

   [[  8  22]
    [  2  20]
    [  2  22]
    [  4  20]
    [  7  22]
    [  7   2]
    [ 22   5]]]


  [[[  9  20]
    [ 13  31]
    [  8  21]
    [ 13  25]
    [  9  29]
    [ 15  20]
    [ 10  25]]

   [[ 13  23]
    [  9  23]
    [ 13  21]
    [-13  32]
    [ 15  25]
    [ 13  31]
    [ 15  29]]

   [[  9  24]
    [  6  26]
    [ 50  30]
    [ 10  30]
    [  7  30]
    [ 12  22]
    [ 11  32]]

   [[ 13  30]
    [ 12  26]
    [ 15  26]
    [ 15  29]
    [  8  25]
    [ 11  27]
    [ 15  24]]]


  [[[  6  20]
    [ 13  32]
    [ 13  28]
    [ 15  25]
    [ 10  31]
    [ 12  23]
    [ 13  30]]

   [[  9  32]
    [  6  32]
    [  8  30]
    [  7  32]
    [  7  32]
    [ 14  29]
    [  9  21]]

   [[ 14  23]
    [ 11  23]
    [ 14  29]
    [ 15  23]
    [ 15  30]
    [ 10  31]
    [ 13  30]]

   [[ 13  24]
    [ 10  29]
    [ 12  24]
    [  6  31]
    [ 13  31]
    [ 13  29]
    [  7  25]]]


  [[[  7  22]
    [ 10  19]
    [-10  18]
    [ 11  20]
    [  8  20]
    [  9  25]
    [ 22  10]]

   [[  8  22]
    [  9  21]
    [ 10  22]
    [  8  19]
    [  9  18]
    [ 11  11]
    [ 18  11]]

   [[  8  21]
    [ 11  20]
    [  8  22]
    [ 10  18]
    [  7  18]
    [  7   7]
    [ 19   7]]

   [[  7  19]
    [  9  22]
    [  8  22]
    [ 11  18]
    [ 12  22]
    [  8  11]
    [ 21   8]]]]



 [[[[  9  20]
    [ 13  31]
    [  8  21]
    [ 13  25]
    [  9  29]
    [ 15  20]
    [ 10  25]]

   [[ 13  23]
    [  9  23]
    [ 13  21]
    [-13  32]
    [ 15  25]
    [ 13  31]
    [ 15  29]]

   [[  9  24]
    [  6  26]
    [ 50  30]
    [ 10  30]
    [  7  30]
    [ 12  22]
    [ 11  32]]

   [[ 13  30]
    [ 12  26]
    [ 15  26]
    [ 15  29]
    [  8  25]
    [ 11  27]
    [ 15  24]]]


  [[[  7  22]
    [ 10  19]
    [-10  18]
    [ 11  20]
    [  8  20]
    [  9  25]
    [ 22  10]]

   [[  8  22]
    [  9  21]
    [ 10  22]
    [  8  19]
    [  9  18]
    [ 11  11]
    [ 18  11]]

   [[  8  21]
    [ 11  20]
    [  8  22]
    [ 10  18]
    [  7  18]
    [  7   7]
    [ 19   7]]

   [[  7  19]
    [  9  22]
    [  8  22]
    [ 11  18]
    [ 12  22]
    [  8  11]
    [ 21   8]]]


  [[[  8  18]
    [  4  19]
    [  6  18]
    [  2  22]
    [  2  18]
    [  2   5]
    [ 21   5]]

   [[  7  20]
    [  3  21]
    [  3  20]
    [  5  20]
    [  3  18]
    [  2   6]
    [ 20   6]]

   [[  4  19]
    [  5  21]
    [  5  18]
    [  5  21]
    [  3  19]
    [  7   6]
    [ 22   4]]

   [[  8  22]
    [  2  20]
    [  2  22]
    [  4  20]
    [  7  22]
    [  7   2]
    [ 22   5]]]


  [[[  6  20]
    [ 13  32]
    [ 13  28]
    [ 15  25]
    [ 10  31]
    [ 12  23]
    [ 13  30]]

   [[  9  32]
    [  6  32]
    [  8  30]
    [  7  32]
    [  7  32]
    [ 14  29]
    [  9  21]]

   [[ 14  23]
    [ 11  23]
    [ 14  29]
    [ 15  23]
    [ 15  30]
    [ 10  31]
    [ 13  30]]

   [[ 13  24]
    [ 10  29]
    [ 12  24]
    [  6  31]
    [ 13  31]
    [ 13  29]
    [  7  25]]]]



 [[[[  9  20]
    [ 13  31]
    [  8  21]
    [ 13  25]
    [  9  29]
    [ 15  20]
    [ 10  25]]

   [[ 13  23]
    [  9  23]
    [ 13  21]
    [-13  32]
    [ 15  25]
    [ 13  31]
    [ 15  29]]

   [[  9  24]
    [  6  26]
    [ 50  30]
    [ 10  30]
    [  7  30]
    [ 12  22]
    [ 11  32]]

   [[ 13  30]
    [ 12  26]
    [ 15  26]
    [ 15  29]
    [  8  25]
    [ 11  27]
    [ 15  24]]]


  [[[  6  20]
    [ 13  32]
    [ 13  28]
    [ 15  25]
    [ 10  31]
    [ 12  23]
    [ 13  30]]

   [[  9  32]
    [  6  32]
    [  8  30]
    [  7  32]
    [  7  32]
    [ 14  29]
    [  9  21]]

   [[ 14  23]
    [ 11  23]
    [ 14  29]
    [ 15  23]
    [ 15  30]
    [ 10  31]
    [ 13  30]]

   [[ 13  24]
    [ 10  29]
    [ 12  24]
    [  6  31]
    [ 13  31]
    [ 13  29]
    [  7  25]]]


  [[[  7  22]
    [ 10  19]
    [-10  18]
    [ 11  20]
    [  8  20]
    [  9  25]
    [ 22  10]]

   [[  8  22]
    [  9  21]
    [ 10  22]
    [  8  19]
    [  9  18]
    [ 11  11]
    [ 18  11]]

   [[  8  21]
    [ 11  20]
    [  8  22]
    [ 10  18]
    [  7  18]
    [  7   7]
    [ 19   7]]

   [[  7  19]
    [  9  22]
    [  8  22]
    [ 11  18]
    [ 12  22]
    [  8  11]
    [ 21   8]]]


  [[[  8  18]
    [  4  19]
    [  6  18]
    [  2  22]
    [  2  18]
    [  2   5]
    [ 21   5]]

   [[  7  20]
    [  3  21]
    [  3  20]
    [  5  20]
    [  3  18]
    [  2   6]
    [ 20   6]]

   [[  4  19]
    [  5  21]
    [  5  18]
    [  5  21]
    [  3  19]
    [  7   6]
    [ 22   4]]

   [[  8  22]
    [  2  20]
    [  2  22]
    [  4  20]
    [  7  22]
    [  7   2]
    [ 22   5]]]]]

22. Create an array that stores the difference between the min and max
temp for each day in all the winter months.

In [ ]:
c1=a[0:,0:,0:,0]
c2=a[0:,0:,0:,1]
c3=c1-c2
print(c3)

23. Find and store the difference between the max temp of two consecutive
days for each month of winter season.

In [ ]:
# Extract max temperature values for each day
max_temps = a[:, :, :, 1]
print(max_temps.shape)
# Calculate the difference between max temperatures of consecutive days
diff_consecutive_days1 = np.diff(max_temps, axis=2)

print("Difference between max temps of consecutive days:\n", diff_consecutive_days)

24. Find and store the difference between the minimum temp of two
consecutive days for each month of the winter season.

In [ ]:
# Extract min temperature values for each day
min_temps = a[:, :, :, 0]
print(min_temps.shape)
# Calculate the difference between min temperatures of consecutive days
diff_consecutive_days2 = np.diff(min_temps, axis=2)

print("Difference between min temps of consecutive days:\n", diff_consecutive_days)

25. Create an array by combining the data present in arrays created in q.23
and q.24, to store the difference between the min and max temp of each
day of all the months for the whole winter season, in a single array

In [ ]:
final_diff = diff_consecutive_days1 - diff_consecutive_days2
print(final_diff)

# Assignment 2